# Generated by Django 6.0.5 on 2026-05-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload de vídeo direto', null=True, upload_to='aulas/videos/'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL externa (YouTube, Vimeo, Google Drive)'),
        ),
    ]
