# Generated by Django 6.0.5 on 2026-05-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_aula_video_file_alter_aula_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='apostila',
            field=models.FileField(blank=True, help_text='Material de apoio em PDF', null=True, upload_to='aulas/apostilas/'),
        ),
    ]
